server:
  address: 0.0.0.0:2811
  idleTimeout: 90s
  readTimeout: 10s
  writeTimeout: 15s
log:
  level: info
postgres:
  name: simpleschedule
  host: postgres
  port: 5432
  user: simpleschedule_user
  password: simpleschedule_9876
  sslmode: disable
  maxOpenConns: 10
  maxIdleConns: 10
  maxIdleTime: 15m