services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: simpleschedule-api
    restart: unless-stopped
    ports:
      - "2811:2811"
    environment:
      CONFIG_PATH: /app/config.yaml
    volumes:
      - ./config.yaml:/app/config.yaml:ro
      - ./storage:/app/storage
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:17-alpine
    container_name: simpleschedule-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: simpleschedule
      POSTGRES_USER: simpleschedule_user
      POSTGRES_PASSWORD: simpleschedule_9876
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U simpleschedule_user -d simpleschedule" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
