// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/slots": {
            "post": {
                "description": "Create a new schedule slot with time range and day validation",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "slots"
                ],
                "summary": "Create slot",
                "parameters": [
                    {
                        "description": "Slot creation payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.CreateSlotRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/handlers.IDResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apierror.UserError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/apierror.UserError"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/apierror.UserError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apierror.UserError"
                        }
                    }
                }
            }
        },
        "/api/slots/{id}": {
            "get": {
                "description": "Retrieve a single schedule slot with its associated tag by its unique identifier",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "slots"
                ],
                "summary": "Get slot by ID",
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"d40c6c2b-e48f-4cb1-80a5-f8c5b6b801a2\"",
                        "description": "Slot ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.SlotResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apierror.UserError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/apierror.UserError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apierror.UserError"
                        }
                    }
                }
            },
            "put": {
                "description": "Update details of an existing slot with collision validation",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "slots"
                ],
                "summary": "Update slot",
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"d40c6c2b-e48f-4cb1-80a5-f8c5b6b801a2\"",
                        "description": "Slot ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Slot update payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.UpdateSlotRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.IDResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apierror.UserError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/apierror.UserError"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/apierror.UserError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apierror.UserError"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a schedule slot by its unique identifier",
                "tags": [
                    "slots"
                ],
                "summary": "Delete slot",
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"d40c6c2b-e48f-4cb1-80a5-f8c5b6b801a2\"",
                        "description": "Slot ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apierror.UserError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/apierror.UserError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apierror.UserError"
                        }
                    }
                }
            }
        },
        "/api/tags": {
            "get": {
                "description": "Retrieve a list of all tags",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tags"
                ],
                "summary": "Get all tags",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.TagsResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apierror.UserError"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new tag with title and hex color",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tags"
                ],
                "summary": "Create tag",
                "parameters": [
                    {
                        "description": "Tag creation payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.CreateTagRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/handlers.IDResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apierror.UserError"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/apierror.UserError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apierror.UserError"
                        }
                    }
                }
            }
        },
        "/api/tags/{id}": {
            "get": {
                "description": "Retrieve a single tag by its unique identifier",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tags"
                ],
                "summary": "Get tag by ID",
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"d40c6c2b-e48f-4cb1-80a5-f8c5b6b801a2\"",
                        "description": "Tag ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.TagResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apierror.UserError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/apierror.UserError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apierror.UserError"
                        }
                    }
                }
            },
            "put": {
                "description": "Update title and hex color of an existing tag",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tags"
                ],
                "summary": "Update tag",
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"d40c6c2b-e48f-4cb1-80a5-f8c5b6b801a2\"",
                        "description": "Tag ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Tag update payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.UpdateTagRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.IDResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apierror.UserError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/apierror.UserError"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/apierror.UserError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apierror.UserError"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a tag by its ID",
                "tags": [
                    "tags"
                ],
                "summary": "Delete tag",
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"d40c6c2b-e48f-4cb1-80a5-f8c5b6b801a2\"",
                        "description": "Tag ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apierror.UserError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/apierror.UserError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apierror.UserError"
                        }
                    }
                }
            }
        },
        "/api/weeks": {
            "get": {
                "description": "Retrieve a list of all schedule weeks",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "weeks"
                ],
                "summary": "Get all weeks",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.WeeksResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apierror.UserError"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new schedule week with title",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "weeks"
                ],
                "summary": "Create week",
                "parameters": [
                    {
                        "description": "Week creation payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.CreateWeekRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/handlers.IDResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apierror.UserError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apierror.UserError"
                        }
                    }
                }
            }
        },
        "/api/weeks/{id}": {
            "get": {
                "description": "Retrieve a single week by its unique identifier",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "weeks"
                ],
                "summary": "Get week by ID",
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"d40c6c2b-e48f-4cb1-80a5-f8c5b6b801a2\"",
                        "description": "Week ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.WeekResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apierror.UserError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/apierror.UserError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apierror.UserError"
                        }
                    }
                }
            },
            "put": {
                "description": "Update the title of an existing week",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "weeks"
                ],
                "summary": "Update week",
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"d40c6c2b-e48f-4cb1-80a5-f8c5b6b801a2\"",
                        "description": "Week ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Week update payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.UpdateWeekRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.IDResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apierror.UserError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/apierror.UserError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apierror.UserError"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a week and cascade delete all its slots",
                "tags": [
                    "weeks"
                ],
                "summary": "Delete week",
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"d40c6c2b-e48f-4cb1-80a5-f8c5b6b801a2\"",
                        "description": "Week ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apierror.UserError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/apierror.UserError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apierror.UserError"
                        }
                    }
                }
            }
        },
        "/api/weeks/{id}/schedule": {
            "get": {
                "description": "Retrieve the complete schedule for a week including all slots grouped by days",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "weeks"
                ],
                "summary": "Get week schedule",
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"d40c6c2b-e48f-4cb1-80a5-f8c5b6b801a2\"",
                        "description": "Week ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.WeekScheduleResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apierror.UserError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/apierror.UserError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apierror.UserError"
                        }
                    }
                }
            }
        },
        "/api/weeks/{id}/slots": {
            "get": {
                "description": "Retrieve all schedule slots with tags for a given week",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "slots"
                ],
                "summary": "Get slots by week ID",
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"d40c6c2b-e48f-4cb1-80a5-f8c5b6b801a2\"",
                        "description": "Week ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.SlotsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apierror.UserError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/apierror.UserError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apierror.UserError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "apierror.UserError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "domain.DayOfWeek": {
            "type": "string",
            "enum": [
                "monday",
                "tuesday",
                "wednesday",
                "thursday",
                "friday",
                "saturday",
                "sunday"
            ],
            "x-enum-varnames": [
                "Monday",
                "Tuesday",
                "Wednesday",
                "Thursday",
                "Friday",
                "Saturday",
                "Sunday"
            ]
        },
        "domain.SlotWithTag": {
            "type": "object",
            "properties": {
                "activity": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "dayOfWeek": {
                    "$ref": "#/definitions/domain.DayOfWeek"
                },
                "endTime": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "startTime": {
                    "type": "integer"
                },
                "tag": {
                    "$ref": "#/definitions/domain.Tag"
                },
                "tagId": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "weekId": {
                    "type": "string"
                }
            }
        },
        "domain.Tag": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "hexColor": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "domain.Week": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "domain.WeekSchedule": {
            "type": "object",
            "properties": {
                "days": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "array",
                        "items": {
                            "$ref": "#/definitions/domain.SlotWithTag"
                        }
                    }
                },
                "slots": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.SlotWithTag"
                    }
                },
                "week": {
                    "$ref": "#/definitions/domain.Week"
                }
            }
        },
        "handlers.CreateSlotRequest": {
            "type": "object",
            "required": [
                "activity",
                "dayOfWeek",
                "weekId"
            ],
            "properties": {
                "activity": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 1,
                    "example": "Higher Mathematics"
                },
                "dayOfWeek": {
                    "enum": [
                        "monday",
                        "tuesday",
                        "wednesday",
                        "thursday",
                        "friday",
                        "saturday",
                        "sunday"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/domain.DayOfWeek"
                        }
                    ],
                    "example": "monday"
                },
                "endTime": {
                    "type": "integer",
                    "maximum": 86400,
                    "minimum": 0,
                    "example": 39600
                },
                "startTime": {
                    "type": "integer",
                    "maximum": 86400,
                    "minimum": 0,
                    "example": 36000
                },
                "tagId": {
                    "type": "string",
                    "example": "97ec8552-9562-4d79-ab4c-1ca959663629"
                },
                "weekId": {
                    "type": "string",
                    "example": "d40c6c2b-e48f-4cb1-80a5-f8c5b6b801a2"
                }
            }
        },
        "handlers.CreateTagRequest": {
            "type": "object",
            "required": [
                "hexColor",
                "title"
            ],
            "properties": {
                "hexColor": {
                    "type": "string",
                    "example": "#FF5733"
                },
                "title": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 1,
                    "example": "Lecture"
                }
            }
        },
        "handlers.CreateWeekRequest": {
            "type": "object",
            "required": [
                "title"
            ],
            "properties": {
                "title": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 1,
                    "example": "Spring Semester 2026"
                }
            }
        },
        "handlers.IDResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "example": "97ec8552-9562-4d79-ab4c-1ca959663629"
                }
            }
        },
        "handlers.SlotResponse": {
            "type": "object",
            "properties": {
                "slot": {
                    "$ref": "#/definitions/domain.SlotWithTag"
                }
            }
        },
        "handlers.SlotsResponse": {
            "type": "object",
            "properties": {
                "slots": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.SlotWithTag"
                    }
                }
            }
        },
        "handlers.TagResponse": {
            "type": "object",
            "properties": {
                "tag": {
                    "$ref": "#/definitions/domain.Tag"
                }
            }
        },
        "handlers.TagsResponse": {
            "type": "object",
            "properties": {
                "tags": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.Tag"
                    }
                }
            }
        },
        "handlers.UpdateSlotRequest": {
            "type": "object",
            "required": [
                "activity",
                "dayOfWeek",
                "weekId"
            ],
            "properties": {
                "activity": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 1,
                    "example": "Physics Lecture"
                },
                "dayOfWeek": {
                    "enum": [
                        "monday",
                        "tuesday",
                        "wednesday",
                        "thursday",
                        "friday",
                        "saturday",
                        "sunday"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/domain.DayOfWeek"
                        }
                    ],
                    "example": "monday"
                },
                "endTime": {
                    "type": "integer",
                    "maximum": 86400,
                    "minimum": 0,
                    "example": 39600
                },
                "startTime": {
                    "type": "integer",
                    "maximum": 86400,
                    "minimum": 0,
                    "example": 36000
                },
                "tagId": {
                    "type": "string",
                    "example": "97ec8552-9562-4d79-ab4c-1ca959663629"
                },
                "weekId": {
                    "type": "string",
                    "example": "d40c6c2b-e48f-4cb1-80a5-f8c5b6b801a2"
                }
            }
        },
        "handlers.UpdateTagRequest": {
            "type": "object",
            "required": [
                "hexColor",
                "title"
            ],
            "properties": {
                "hexColor": {
                    "type": "string",
                    "example": "#33FF57"
                },
                "title": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 1,
                    "example": "Practice"
                }
            }
        },
        "handlers.UpdateWeekRequest": {
            "type": "object",
            "required": [
                "title"
            ],
            "properties": {
                "title": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 1,
                    "example": "Autumn Semester 2026"
                }
            }
        },
        "handlers.WeekResponse": {
            "type": "object",
            "properties": {
                "week": {
                    "$ref": "#/definitions/domain.Week"
                }
            }
        },
        "handlers.WeekScheduleResponse": {
            "type": "object",
            "properties": {
                "schedule": {
                    "$ref": "#/definitions/domain.WeekSchedule"
                }
            }
        },
        "handlers.WeeksResponse": {
            "type": "object",
            "properties": {
                "weeks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.Week"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:2811",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "SimpleSchedule API",
	Description:      "SimpleSchedule service API.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
